language: android
# jdk: oraclejdk8

os:
  - linux
  
android:
  components:
#    - yes | sdkmanager --licenses && yes | sdkmanager --update
    - build-tools-28.0.3
    - android-28
    - extra
  licenses:
    # - 'android-sdk-preview-license-.*'
    # - 'android-sdk-license-.+'
    # - 'google-gdk-license-.+'
    - '.+'
script:
    - ./gradlew assembleDebug
    